"""Add type to Category

Revision ID: 671bf8db5524
Revises: 265e99be823a
Create Date: 2025-12-13 00:24:40.251858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671bf8db5524'
down_revision: Union[str, Sequence[str], None] = '265e99be823a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Thêm server_default='EXPENSE' để các bản ghi hiện có không bị lỗi khi thêm cột NOT NULL
    op.add_column(
        'categories', 
        sa.Column(
            'type', 
            sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontype'), 
            nullable=False, 
            server_default='EXPENSE'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###